// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxrsQkn12W8WpDdxf22rKdhZb9Wk9Wb4',
    appId: '1:452578317638:web:59d7c7c12fa05204f54147',
    messagingSenderId: '452578317638',
    projectId: 'smartstation-374b5',
    authDomain: 'smartstation-374b5.firebaseapp.com',
    storageBucket: 'smartstation-374b5.appspot.com',
    measurementId: 'G-33CD3KCYR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2CZdYd3bEVLoMeIJ9XRmKZx_9PmNubU4',
    appId: '1:452578317638:android:c7754a635d4a70aff54147',
    messagingSenderId: '452578317638',
    projectId: 'smartstation-374b5',
    storageBucket: 'smartstation-374b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA728BxgF5Jg9bdo2EgSGgASOCtP_slR7g',
    appId: '1:452578317638:ios:788cdd93092b1893f54147',
    messagingSenderId: '452578317638',
    projectId: 'smartstation-374b5',
    storageBucket: 'smartstation-374b5.appspot.com',
    iosClientId: '452578317638-ahld05gajp2rr9nv5aalu8nq12kvc8dl.apps.googleusercontent.com',
    iosBundleId: 'com.cal.smartstation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA728BxgF5Jg9bdo2EgSGgASOCtP_slR7g',
    appId: '1:452578317638:ios:4aa9ea6e33bb119af54147',
    messagingSenderId: '452578317638',
    projectId: 'smartstation-374b5',
    storageBucket: 'smartstation-374b5.appspot.com',
    iosClientId: '452578317638-s5plt6he95tbjv83lrqjhq93tshop45p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStation',
  );
}
